cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('download/<int:id>/', views.order_items_download, name='order_download'),
    path('redirect-me/<int:id>/', views.redirect_me, name='redirect-me')
]

shop/urls.py
from django.urls import path

from .views import about, contact, product_detail, product_list

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
]

xpiece/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
# from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 12)]


class CartAddProductForm(forms.Form):
    ...
    # quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    # override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from shop.models import Product

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cart.add(product=product)
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Shopping cart{% endblock title %}

{% block content %}
    <div class="grid-container">
        <main class="cart-content">
            <h1>Shopping Cart</h1>
                <div class="cart">

                    <ul class="cart-labels grid-container">
                        <li>Remove</li>
                        <li>Image</li>
                        <li>Product</li>
                        <li>Price</li>
                    </ul>

                    {% for item in cart %}
                        {% with product=item.product %}
                            <ul class="cart-products grid-container">
                                <li class="remove">
                                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="submit" value="x">
                                    </form>
                                </li>
                                <li>
                                    <a href="{{ product.get_absolute_url }}">
                                        <img src="{% if product.thumbnail %}{{product.thumbnail.url}}{% else %}{% static 'images/default_thumbnail.png' %}{% endif %}" alt="">
                                    </a>
                                </li>
                                <li>{{ product.name }}</li>
                                <li>${{ item.price }}</li>
                            </ul>                    
                        {% endwith %}
                    {% endfor %}

                    <ul class="cart-total grid-container">
                        <li class="total-label">Total</li>
                        <li class="total-price">${{ cart.get_total_price }}</li>
                    </ul>

                    <p class="flex-text-space-between">
                        <a href="{% url 'shop:product_list' %}" class="button light">Back</a>
                        <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
                    </p>
                </div>
        </main>
    </div>
{% endblock content %}