cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path

from .views import about, contact, product_detail, product_list

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
]

xpiece/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/product/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ product.name }}{% endblock title %}

{% block content %}
    <main class="product-content grid-container">
        <img src="{% if product.cover %}{{ product.cover.url }}{% else %}{% static 'images/default_cover.png' %}{% endif %}" alt="Product Cover Image" class="cover">
        <div class="product-detail">
            <div class="category-price">
                <h2>
                    <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
                </h2>
                <h6>${{product.price}}</h6>
            </div>
            <h1>{{ product.name }}</h1>
            {{product.description|linebreaks}}

            <hr>

            <div class="product-detail--labels">
                <div class="product-detail--label">
                    <p class="label-title">Formats</p>
                    <p>{% for format in formats %}.{{ format }} {% endfor %}</p>
                </div>
            </div>
            
            <form class="add-to-cart" action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                <input type="submit" class="add-cart--button" value="Add to Cart">
            </form>

        </div>

        {% for screenshot in screenshots %}
            <img src="{{ screenshot.image.url }}" alt="Product Cover Image" class="cover">
        {% endfor %}
    </main>
{% endblock content %}

templates/product/list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section class="hero grid-container">
        <div class="value-proposition">
            <h2>Improve your development workflow.</h2>
            <h5>Perhaps your dream design already exists!</h5>
        </div>
    </section>

    <section class="grid-container">
        <nav class ="categories-nav">
            <a href="{% url 'shop:product_list' %}" class="active">All</a>

            {% for category in categories %}
                    <a href="{{ category.get_absolute_url}}">{{ category.name }}</a>
            {% endfor %}
        </nav>
    </section>

    <main class="product-list grid-container">
        {% for product in products %}
            <div class="product-card">
                <div class="thumbnail">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.thumbnail %}{{product.thumbnail.url }} {% else %}{% static "images/default_thumbnail.png" %} {% endif %}" alt="">
                    </a>
                </div>
                
                <div class="label">
                    <div class="category-price-text">
                        <p>{% if product.category %}{{ product.category.name }}{% endif %}</p>
                        <div class="price">
                            <span>$</span><h6>{{ product.price }}</h6>
                        </div>
                    </div>
                    <a href="{{ product.get_absolute_url }}">
                        <h6>{{ product.name }}</h6>
                    </a>                 
                </div>                
            </div>
        {% endfor %}
    </main>
{% endblock content %}