cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path

from .views import about, contact, product_detail, product_list

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
]

xpiece/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/dashboard-menu.html
{% load static %}

<aside class="dashboard-menu">
            
    <div class="dashboard-menu-header">
        <img class="icon" src="{{ user.profile.picture.url }}" alt="">
        <h6 class="profile-username">{{ user.first_name }} {{ user.last_name }}</h6>
    </div>

    <nav>
        <li>
            <div class="icon">
                <i class="fa-solid fa-user"></i>
            </div>
            <a class="title" href="{% url 'profile' %}">Profile</a>
        </li>
        <li>
            <div class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
            </div>
            <a class="title" href="{% url 'profile_orders' %}">Orders</a>
        </li>
        <li>
            <div class="icon">
                <i class="fa-solid fa-bag-shopping"></i>
            </div>                
            <a class="title" href="{% url 'profile' %}">Products</a>
        </li>
        <li>
            <div class="icon">
                <i class="fa-solid fa-money-bill"></i>
            </div>
            <a class="title" href="{% url 'profile' %}">Payments</a>
        </li>
    </nav>
</aside>

templates/components/footer.html
<footer>
    <div class="grid-container">
        <div id="footer-menus">
            <div id="footer-categories">
                <h5>Categories</h5>
                {% for category in categories %}
                    <a href="{{ category.get_absolute_url}}">{{ category.name }}</a>
                {% endfor %}
            </div>
        </div>
        
        <div id="footer-contact">
            <div id="social-media">
                <h6>Connect with us</h6>
                <div id="social-media-icons">
                    <a href="#">
                        <i class="fa-brands fa-dribbble"></i>
                    </a>
                    <a href="#">
                        <i class="fa-brands fa-behance"></i>
                    </a>
                    <a href="#">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                    <a href="#">
                        <i class="fa-brands fa-x-twitter"></i>
                    </a>
                </div>
            </div>

            <div id="newsletter">
                <h6>Join our newsletter</h6>
                <form action="">
                    <input type="email" name="newsletter" placeholder="Insert your email...">
                </form>
            </div>
        </div>

        <div id="footer-visit">
            <h5>Contact Us</h5>
            <p>Av. Guedner, nº 1610 - Bloco 11</p>
            <p>Jardim Aclimação</p>
            <p>Maringá / PR</p>
            <br>
            <p>55 44 3027 6360</p>
            <p>0800 604 4422</p>
        </div>

        <div id="copyright">
            <i class="fa-regular fa-copyright"></i>
            <p>2023 - Xpiece | All Rights Reserved</p>
        </div>
    </div>
</footer>

templates/components/header.html
{% load static %}
<header class="grid-container">
    <div id="logo">
        <a href="/">
            <img src="{% static 'images/logo.png' %}" alt="Company Logo">
        </a>
    </div>

    <nav id="navbar">
        <a class="navbar-item {% if request.resolver_match.url_name == 'product_list' %}active{% endif %}" href="{% url 'shop:product_list' %}" >Shop</a>
        <a class="navbar-item {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="{% url 'shop:about' %}" >About</a>
        <a class="navbar-item {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'shop:contact' %}">Contact</a>
    </nav>

    <div id="icons-navbar">
        {% if request.user.is_authenticated %}
            <a href="{% url 'dashboard' %}">{{ request.user.first_name|default:request.user.username }}</a>
            <a href="{% url 'logout' %}">Logout</i></a>
        {% else %}
            <a href="{% url 'register' %}">Register</a>
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
        <a href="{% url "cart:cart_detail" %}"><i class="fa-solid fa-cart-shopping"></i>
        {% with items=cart|length %}
            {% if items > 0 %}
                <span class="cart-number">{{ cart|length }}</span>
            {% endif %}     
        {% endwith %}
        </a>
    </div>
</header>