cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

payment/urls.py
from django.urls import path

from . import views, webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/<int:id>/<slug:token>/', views.payment_completed, name='completed'),
    path('canceled/<int:id>/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

shop/urls.py
from django.urls import path

from .views import about, contact, product_detail, product_list

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
]

xpiece/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/views.py
from decimal import Decimal

import stripe
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render, reverse

from orders.models import Order

from .tasks import send_email_after_payment

# Instanciando stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed', kwargs={'id':order.id, 'token':order.token}))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled', kwargs={'id':order.id}))
        # Criando dados de checkout para o Stripe
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        # Adicionando os items da ordem na sessão de checkout do Stripe
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    # O pagamento do Stripe é em centavos, por isso a multiplicação por 100
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                'quantity': int(1),
            })

        # Criando a sessão de checkout para o Stripe usando os dados
        session = stripe.checkout.Session.create(**session_data)
        # Redirecionando para formulário de pagamento do Stripe
        return redirect(session.url, code=303)

    else:
        return render(request, 'payment/process.html', locals())

@login_required
def payment_completed(request, id, token):
    order = get_object_or_404(Order, id=id)
    order.generate_url(request)
    url = request.build_absolute_uri(reverse('payment:completed', kwargs={'id':order.id, 'token':order.token}))
    send_email_after_payment(order, url)
    context = {'order': order}
    return render(request, 'payment/completed.html', context)


def payment_canceled(request, id):
    order = get_object_or_404(Order, id=id)
    context = {'order': order}
    return render(request, 'payment/canceled.html', context)

templates/payment/canceled.html
{% extends "base.html" %}
{% block title %}Payment Canceled{% endblock %}

{% block content %}
    <div class="grid-container">
        <div class="payment-processed">
            <h1>Your payment has not been processed</h1>
            <p>There was a problem processing your payment.</p>
            <p>
                <a href="{% url 'shop:product_list' %}" class="button light">Back</a>
            </p>
        </div>
    </div>
{% endblock %}

templates/payment/completed.html
{% extends "base.html" %}
{% load static %}

{% block title %}Payment Successful{% endblock %}

{% block content %}
    <div class="grid-container">
        <main class="payment-processed">
            <h1>Thank you for your purchase</h1>
            <p>Your payment has been processed successfully.</p>
            <p>Download your files below...</p>

            {% for item in order.items.all  %}
                {% with product=item.product %}
                    <ul class="download-products grid-container">
                        <li>
                            <img src="{% if product.thumbnail %}{{product.thumbnail.url}}{% else %}{% static 'images/default_thumbnail.png' %}{% endif %}" alt="">
                        </li>
                        <li><h6>{{ product.name }}</h6></li>
                        <li>{{ product.category }}</li>
                        <li class="download-btn-col">
                            <a href="{{ product.file.url }}" class="button">download</a>
                        </li>
                    </ul>                    
                {% endwith %}                
            {% endfor %}

            <p>
                <a href="{% url 'shop:product_list' %}" class="button light">Return to Store</a>
            </p>
        </main>
    </div>
{% endblock %}

templates/payment/process.html
{% extends "base.html" %}
{% load static %}

{% block title %}Payment{% endblock title %}

{% block content %}
    <main class="payment-content">
        <h1>Your Order</h1>
        <div class="payment">
            <ul class="payment-labels grid-container">
                <li class="image">Image</li>
                <li>Product</li>
                <li class="price">Price</li>
            </ul>

            {% for item in order.items.all %}
                <ul class="payment-products grid-container">
                    <li>
                        <img src="{% if item.product.thumbnail %}{{ item.product.thumbnail.url }}{% else %}{% static 'images/default_thumbnail.png' %}{% endif %}">
                    </li>
                    <li>{{ item.product.name }}</li>
                    <li class="price">${{ item.price }}</li>
                </ul>
            {% endfor %}

            <ul class="payment-total grid-container">
                <li class="total-label">Total</li>
                <li class="total-price">${{ order.get_total }}</li>
            </ul>

            <form action="{% url 'payment:process' %}" method="post">
                <input class="payment-button" type="submit" value="Pay Now">
                {% csrf_token %}
            </form>
        </div>
    </main>

{% endblock content %}